Repository TheRenegadeCoder/sample-programs-website, pull requests merged in 2020-10, with the labels that each got.

#318 Added the Hello World article for Tex.
  projects/hello-world/_posts/2020-09-30-tex.md
Labels: sample program

#319 Added the Hello World Article for TypeScript
  projects/hello-world/_posts/2020-09-30-typescript.md
Labels: sample program

#317 Add the Bubble Sort Article for Go.
  projects/bubble-sort/_posts/2020-09-30-go.md
Labels: sample program

#322 Added Hello World Article how to run section for Tex.
  projects/hello-world/_posts/2020-09-30-tex.md
Labels: enhancement

#320 Added the Hello World Article for Emojicode.
  projects/hello-world/_posts/2020-09-30-emojicode.md
Labels: sample program

#323 Updated the how to Run Section for Hello World Article of Typescript.
  projects/hello-world/_posts/2020-09-30-typescript.md
Labels: sample program

#326 Added Bio to Authors File
  _data/authors.yml
Labels: enhancement

#336 Created an article for FizzBuzz in C.
  _data/authors.yml
  projects/fizz-buzz/_posts/2020-10-05-c.md
Labels: sample program

#329 Added Depth First Search in Every Language Article
  projects/depth-first-search/index.md
Labels: project

#338 Added Baklava in C
  projects/baklava/2020-10-05-c.md
Labels: sample program

#339 Moved Baklava in C Article to Posts Folder
  projects/baklava/_posts/2020-10-05-c.md
Labels: bug

#341 Added Even Odd in C Article
  projects/even-odd/_posts/2020-10-06-c.md
Labels: sample program

#342 Updated Several Images to Follow Latest Image Titler Version
  assets/images/hello-world-in-haskell-featured-image.JPEG
  assets/images/sample-programs-in-every-language-featured-image.JPEG
Labels: enhancement

#344 Toying with GitHub Actions
  .github/workflows/main.yml
  _includes/featured_image.html
  assets/images/icon-small.png
  assets/images/sample-programs-in-every-language-featured-image.JPEG
  assets/images/sample-programs-in-every-language.jpg
  assets/sources/sample-programs-in-every-language.jpg
Labels: enhancement

#345 Added Featured Image to Baklava in Every Language
  assets/images/baklava-in-every-language.jpg
  assets/sources/baklava-in-every-language.jpg
  projects/baklava/index.md
Labels: enhancement

#331 Added Josephus Problem in Every Language Article
  _data/authors.yml
  projects/josephus-problem/index.md
Labels: project

#346 Added Ways to Contribute to README
  README.md
Labels: enhancement

#347 Added Binary Search in Every Language Featured Image
  assets/images/binary-search-in-every-language.jpg
  assets/sources/binary-search-in-every-language.jpg
  projects/binary-search/index.md
Labels: enhancement

#349 Added Palindromic Numbers in Every Language Article
  _data/authors.yml
  projects/palindromic-numbers/_posts/2020-10-07-kotlin.md
  projects/palindromic-numbers/index.md
Labels: project

#350 Added More Specific Expectations in Project Template
  templates/PROJECT_ARTICLE_TEMPLATE.md
Labels: enhancement

#328 Added Pull Request Template
  pull_request_template.md
Labels: enhancement

#330 Added Transpose Matrix in Every Language Article
  _data/authors.yml
  projects/transpose matrix/index.md
Labels: project

#352 Sorted Authors File Alphabetically
  _data/authors.yml
Labels: enhancement

#353 Reworked the Transpose Matrix Documentation
  projects/transpose matrix/index.md
  projects/transpose-matrix/index.md
Labels: enhancement

#355 Added GoodbyeBlues to Authors
  _data/authors.yml
Labels: enhancement

#334 Added Duplicate Character Counter in Every Language Article
  projects/duplicate-char-counter/index.md
Labels: project

#356 Added Bubble Sort Featured Image
  assets/images/bubble-sort-in-every-language.jpg
  assets/sources/bubble-sort-in-every-language.jpg
  projects/bubble-sort/index.md
Labels: enhancement

#358 Added Fibonacci in Python Article and Added Some Images
  projects/baklava/_posts/2020-10-05-c.md
  projects/binary-search/_posts/2018-12-19-python.md
  projects/bubble-sort/_posts/2020-09-30-go.md
  projects/even-odd/_posts/2019-10-16-python.md
  projects/even-odd/_posts/2020-10-06-c.md
  projects/fibonacci/_posts/2020-10-13-python.md
  projects/fizz-buzz/_posts/2018-11-06-java.md
  projects/fizz-buzz/_posts/2018-11-24-swift.md
  projects/fizz-buzz/_posts/2018-12-11-powershell.md
  projects/fizz-buzz/_posts/2018-12-15-python.md
  projects/fizz-buzz/_posts/2019-10-01-javascript.md
  projects/fizz-buzz/_posts/2019-10-18-lisp.md
  projects/fizz-buzz/_posts/2020-08-30-befunge.md
  projects/fizz-buzz/_posts/2020-10-05-c.md
  projects/fizz-buzz/index.md
  projects/hello-world/_posts/2018-11-17-red.md
  projects/hello-world/_posts/2018-12-05-rust.md
Labels: enhancement, sample program

#340 Added Maximum Subarray in Every Language Article
  _data/authors.yml
  projects/maximum-subarray/_posts/2020-10-06-python.md
  projects/maximum-subarray/index.md
Labels: project

#361 Enforced Python 3.8 Build
  .github/workflows/main.yml
Labels: bug

#360 Added Testing Table to Linear Search Project
  projects/linear-search/index.md
Labels: enhancement

#363 Added Linear Search in Every Language Featured Image
  assets/images/linear-search-in-every-language.jpg
  assets/sources/linear-search-in-every-language.jpg
  projects/linear-search/index.md
Labels: enhancement

#364 Added Projects in Every Language Featured Image
  assets/images/projects-in-every-language-featured-image.JPEG
  assets/images/projects-in-every-language.jpg
  assets/sources/projects-in-every-language.jpg
  projects/index.md
Labels: project

#366 Updated Several Hello World Featured Images
  projects/hello-world/_posts/2018-11-01-brainfuck.md
  projects/hello-world/_posts/2018-11-01-dart.md
  projects/hello-world/_posts/2018-11-01-lua.md
  projects/hello-world/_posts/2018-11-01-moonscript.md
  projects/hello-world/_posts/2018-11-01-opa.md
  projects/hello-world/_posts/2018-11-01-powershell.md
  projects/hello-world/_posts/2018-11-01-r.md
Labels: sample program

#359 Added Convex Hull Test Cases
  projects/convex-hull/index.md
Labels: hacktoberfest, hacktoberfest-accepted, project

#376 Simplified LPS Testing
  projects/longest-palindrome-substring/index.md
Labels: project

#378 Forced Myself as Commit Author
  .github/workflows/main.yml
Labels: enhancement

#379 Added Credit to TheRenegadeCoder Org to Image Commit
  .github/workflows/main.yml
Labels: enhancement

#373 Added Remove All Whitespace in Every Language Article
  _data/authors.yml
  projects/remove-all-whitespace/index.md
Labels: hacktoberfest-accepted, project

#375 Added Baklava in Kotlin Article
  assets/sources/baklava-in-c.jpg
  assets/sources/baklava-in-kotlin.jpg
  assets/sources/file-io-in-every-language.jpg
  assets/sources/fizz-buzz-in-befunge.jpg
  assets/sources/fizz-buzz-in-java.jpg
  assets/sources/fizz-buzz-in-lisp.jpg
  assets/sources/reverse-a-string-in-c.jpg
  assets/sources/reverse-a-string-in-every-language.jpg
  assets/sources/reverse-a-string-in-python.jpg
  projects/baklava/_posts/2020-10-05-c.md
  projects/baklava/_posts/2020-10-22-kotlin.md
  projects/file-io/index.md
  projects/fizz-buzz/_posts/2018-11-06-java.md
  projects/fizz-buzz/_posts/2019-10-18-lisp.md
  projects/fizz-buzz/_posts/2020-08-30-befunge.md
  projects/reverse-a-string/_posts/2018-12-24-python.md
  projects/reverse-a-string/_posts/2020-10-01-c.md
  projects/reverse-a-string/index.md
Labels: sample program

#381 Rendered Several Images for the Site
  .github/pull_request_template.md
  .github/workflows/main.yml
  assets/images/baklava-in-c.jpg
  assets/images/baklava-in-kotlin.jpg
  assets/images/file-io-in-every-language.jpg
  assets/images/fizz-buzz-in-befunge.jpg
  assets/images/fizz-buzz-in-java.jpg
  assets/images/fizz-buzz-in-lisp.jpg
  assets/images/hello-world-in-matlab.jpg
  assets/images/reverse-a-string-in-c.jpg
  assets/images/reverse-a-string-in-every-language.jpg
  assets/images/reverse-a-string-in-python.jpg
  assets/sources/hello-world-in-matlab.jpg
Labels: enhancement

#351 Added Array Rotation in Every Language Article
  _data/authors.yml
  projects/array-rotation/index.md
Labels: hacktoberfest, project

#384 Added a Description to the Remove All Whitespace Article
  projects/remove-all-whitespace/index.md
Labels: project

#385 Added Fizz Buzz in Kotlin
  projects/fizz-buzz/_posts/2018-11-06-java.md
  projects/fizz-buzz/_posts/2019-10-18-lisp.md
  projects/fizz-buzz/_posts/2020-10-28-kotlin.md
Labels: sample program

#380 Added Longest Word in Every Language Article
  _data/authors.yml
  projects/longest-word/index.md
  projects/remove-all-whitespace/index.md
Labels: project
