Repository TheRenegadeCoder/sample-programs-website, pull requests merged in 2023-04, with the labels that each got.

#534 Fix superscript
  docs/assets/css/style.scss
Labels: bug

#532 Auto-generate test documentation
  .gitignore
  generate.sh
  requirements.txt
  scripts/automate.py
  sources/projects/baklava/testing.md
  sources/projects/binary-search/invalid-tests.md
  sources/projects/binary-search/valid-tests.md
  sources/projects/bubble-sort/invalid-tests.md
  sources/projects/bubble-sort/valid-tests.md
  sources/projects/capitalize/invalid-tests.md
  sources/projects/capitalize/valid-tests.md
  sources/projects/convex-hull/invalid-tests.md
  sources/projects/convex-hull/valid-tests.md
  sources/projects/depth-first-search/invalid-tests.md
  sources/projects/depth-first-search/valid-tests.md
  sources/projects/dijkstra/invalid-tests.md
  sources/projects/dijkstra/valid-tests.md
  sources/projects/duplicate-character-counter/testing.md
  sources/projects/even-odd/testing.md
  sources/projects/factorial/testing.md
  sources/projects/fibonacci/testing.md
  sources/projects/file-input-output/testing.md
  sources/projects/fizz-buzz/testing.md
  sources/projects/fraction-math/testing.md
  sources/projects/hello-world/testing.md
  sources/projects/insertion-sort/testing.md
  sources/projects/job-sequencing/testing.md
  sources/projects/josephus-problem/testing.md
  sources/projects/linear-search/testing.md
  sources/projects/longest-common-subsequence/testing.md
  sources/projects/longest-palindromic-substring/testing.md
  sources/projects/longest-word/testing.md
  sources/projects/maximum-array-rotation/testing.md
  sources/projects/maximum-subarray/testing.md
  sources/projects/merge-sort/testing.md
  sources/projects/minimum-spanning-tree/testing.md
  sources/projects/palindromic-number/invalid-tests.md
  sources/projects/palindromic-number/valid-tests.md
  sources/projects/prime-number/testing.md
  sources/projects/quick-sort/testing.md
  sources/projects/quine/testing.md
  sources/projects/remove-all-whitespace/testing.md
  sources/projects/reverse-string/testing.md
  sources/projects/roman-numeral/testing.md
  sources/projects/rot13/testing.md
  sources/projects/selection-sort/testing.md
  sources/projects/sleep-sort/testing.md
  sources/projects/transpose-matrix/testing.md
Labels: enhancement

#536 Use normal quotes
  docs/_config.yml
Labels: bug

#538 Add Quine in Rust
  sources/images/quine-in-rust.jpg
  sources/programs/quine/rust/front_matter.yaml
  sources/programs/quine/rust/how-to-implement-the-solution.md
  sources/programs/quine/rust/how-to-run-the-solution.md
Labels: sample program, enhancement

#540 Updated Requirements to SnakeMD 2.0.0b1
  requirements.txt
  scripts/automate.py
Labels: enhancement

#541 Incremented to Next Beta Version of SnakeMD 2.0.0b2
  requirements.txt
Labels: enhancement

#543 Add Phix Language Article
  sources/languages/phix/description.md
  sources/languages/phix/front_matter.yaml
Labels: enhancement, language
