Repository TheRenegadeCoder/sample-programs-website, pull requests merged in 2025-03, with the labels that each got.

#646 Update to glotter 0.10.0 and subete 0.20.0
  .github/CONTRIBUTING.md
  .github/workflows/main.yml
  requirements.txt
Labels: dependencies

#644 feat: Add base64 encode decode project article
  poetry.lock
  pyproject.toml
  scripts/automate.py
  sources/projects/base64-encode-decode/description.md
  sources/projects/base64-encode-decode/featured-image.png
  sources/projects/base64-encode-decode/requirements.md
Labels: project

#655 Removed Twitter References
  README.md
  docs/_includes/twitter_card.html
Labels: enhancement
